name: dl-rna
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - pytorch=1.10.0
  - torchvision=0.11.1
  - torchaudio=0.10.0
  - tqdm=4.62.3
  - python=3.8.8
  - numpy=1.20.1
  - scikit-learn=0.24.1
